language: php
php:
  - 7.0
sudo: required
before_script:
  - curl -s http://getcomposer.org/installer | php
script:
  - mkdir -p build/logs
  - composer test
after_script:
  - travis_retry php vendor/bin/coveralls -v